/*
 * i18n_tab.c -- GENERATED by ./tools/i18n.py compile from i18n/<locale>.yml.
 * Do not edit; edit the YAML. Sorted by strcmp() for i18n.c's bsearch.
 * NULL is "not translated": i18n_get() hands back the key.
 *
 * SPDX-License-Identifier: MIT
 */

#include <stddef.h>
#include "i18n.h"

const unsigned i18n_count = 7;
const char *const i18n_keys[] = {
    "%d s",
    "Crossfade   %d s",
    "Crossfade   off",
    "OFF",
    "ON",
    "Same album",
    "off",
};

/* [lang * i18n_count + key] */
const char *const i18n_vals[] = {
    /* en */
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    /* zh-CN */
    "%d 秒",
    "交叉淡化   %d 秒",
    "交叉淡化   关",
    "关",
    "开",
    "同一专辑",
    "关",
    /* ja */
    "%d 秒",
    "クロスフェード   %d 秒",
    "クロスフェード   オフ",
    "オフ",
    "オン",
    "同じアルバム",
    "オフ",
    /* es */
    "%d s",
    "Fundido cruzado   %d s",
    "Fundido cruzado   desactivado",
    "NO",
    "SÍ",
    "Mismo álbum",
    "no",
};

const unsigned i18n_pcount = 0;
const char *const i18n_pkeys[] = {
    NULL,    /* C has no empty arrays */
};

/* [(lang * i18n_pcount + key) * 2 + form], form 0 one, 1 other -- the two
 * categories en, zh, ja and es use between them. */
const char *const i18n_pvals[] = {
    /* en */
    /* zh-CN */
    /* ja */
    /* es */
    NULL,                      /* C has no empty arrays */
};
