#!/usr/bin/env python3
"""
gen_casefold.py -- the canonical decompositions and combining classes
casefold.h normalises with, as main/casefold_tab.c. 5256.

MPD 0.24 applies Unicode normalisation to case-insensitive filter
expressions, so "é" typed as one code point (U+00E9) and as "e" plus a
combining acute (U+0065 U+0301) are the same. casefold.h folds case by
ranges, which cannot do that: where the marks go is not a pattern. So
this is the table, generated rather than typed, from Python's own
unicodedata -- the Unicode Character Database of the Python that runs
it. Decompositions are frozen by Unicode's stability policy, so the
database version changes nothing for the scripts covered; the header
records it anyway.

COVERED: the blocks casefold.h folds, which is where a music library's
accents are -- Latin-1, Latin Extended-A and -B, Greek (and Greek
Extended, whose letters are all decompositions), Cyrillic, Latin
Extended Additional (Vietnamese) -- and the three letterlike singletons
Ω K Å. Hangul syllables decompose by arithmetic in casefold.h. Not
covered: Indic nuktas, CJK compatibility ideographs, the compatibility
(K) forms -- ligatures, full-width, superscripts -- which NFD leaves
alone too.

U+0130 (İ) is left out on purpose: its decomposition is I + U+0307, and
casefold.h folds it to a plain i, which is what a search for "istanbul"
wants.

Usage: ./tools/gen_casefold.py > main/casefold_tab.c

One .c, declared in casefold.h, so the tables are in the firmware once
and not in every file that folds (medialib.c, mpd.c, mpdfilter.c).

SPDX-License-Identifier: MIT
"""

import unicodedata as ud

RANGES = [(0x00C0, 0x024F), (0x0340, 0x03FF), (0x0400, 0x04FF), (0x1E00, 0x1FFF),
          (0x2126, 0x2126), (0x212A, 0x212B)]
SKIP = {0x0130}
# Combining marks whose class matters: the blocks of marks a Latin,
# Greek or Cyrillic accent is written with, and every mark the
# decompositions use.
MARK_RANGES = [(0x0300, 0x036F), (0x0483, 0x0489), (0x1AB0, 0x1AFF), (0x1DC0, 0x1DFF),
               (0x20D0, 0x20FF), (0xFE20, 0xFE2F)]


def main():
    dec = []
    for lo, hi in RANGES:
        for c in range(lo, hi + 1):
            if c in SKIP:
                continue
            d = ud.normalize("NFD", chr(c))
            if d != chr(c):
                cps = [ord(x) for x in d]
                assert all(x < 0x10000 for x in cps) and len(cps) <= 4
                dec.append((c, cps))
    marks = set()
    for lo, hi in MARK_RANGES:
        marks.update(c for c in range(lo, hi + 1) if ud.combining(chr(c)))
    for _, cps in dec:
        marks.update(x for x in cps if ud.combining(chr(x)))
    marks = sorted(marks)

    out = []
    w = out.append
    w("/*")
    w(" * casefold_tab.c -- GENERATED by tools/gen_casefold.py; do not edit.")
    w(f" * Unicode {ud.unidata_version}: {len(dec)} canonical decompositions,")
    w(f" * {len(marks)} combining classes. See casefold.h. 5256.")
    w(" *")
    w(" * SPDX-License-Identifier: MIT")
    w(" */")
    w('#include "casefold.h"')
    w("")
    w(f"_Static_assert(CASEFOLD_NDEC == {len(dec)}, \"regenerate: casefold.h's CASEFOLD_NDEC\");")
    w(f"_Static_assert(CASEFOLD_NCCC == {len(marks)}, \"regenerate: casefold.h's CASEFOLD_NCCC\");")
    w("")
    w("/* Code points with a decomposition, ascending. */")
    w("const uint16_t casefold_dec_cp[CASEFOLD_NDEC] = {")
    for i in range(0, len(dec), 10):
        w("    " + " ".join(f"0x{c:04X}," for c, _ in dec[i:i + 10]))
    w("};")
    pool, offs = [], []
    for _, cps in dec:
        offs.append(len(pool) << 2 | (len(cps) - 1))
        pool.extend(cps)
    assert len(pool) < (1 << 14)
    w("")
    w("/* Each one's full decomposition: pool index << 2 | (length - 1). */")
    w("const uint16_t casefold_dec_at[CASEFOLD_NDEC] = {")
    for i in range(0, len(offs), 10):
        w("    " + " ".join(f"0x{o:04X}," for o in offs[i:i + 10]))
    w("};")
    w("")
    w("const uint16_t casefold_dec_pool[] = {")
    for i in range(0, len(pool), 10):
        w("    " + " ".join(f"0x{c:04X}," for c in pool[i:i + 10]))
    w("};")
    w("")
    w("/* Combining marks and their canonical combining class, ascending. */")
    w("const uint16_t casefold_ccc_cp[CASEFOLD_NCCC] = {")
    for i in range(0, len(marks), 10):
        w("    " + " ".join(f"0x{c:04X}," for c in marks[i:i + 10]))
    w("};")
    w("const uint8_t casefold_ccc[CASEFOLD_NCCC] = {")
    for i in range(0, len(marks), 16):
        w("    " + " ".join(f"{ud.combining(chr(c))}," for c in marks[i:i + 16]))
    w("};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
