# 5283: the libraries this build was made from, for the settings panel's
# BUILD tab -- written as a header, libversions.h, that main includes.
#
# From the records the build itself uses, so the screen cannot drift
# from what was compiled:
#
#   dependencies.lock        every managed component and the version the
#                            component manager resolved (git ones by commit)
#   cmake/vendored.cmake     the commits minimp3, pngle and stb_image are
#                            fetched at (MINIMP3_COMMIT etc., set before
#                            project() and so in scope here)
#   components/usb_host_*/   the vendored USB class drivers' own manifests;
#     idf_component.yml      both carry fixes past that version (5026, 5035)
#   tools/gen_ark12.py       the Ark Pixel commit the font was cut from
#
# Include AFTER project(). Sets LIBVERSIONS_DIR to the directory holding
# libversions.h. The header is rewritten only when its text changes, so
# an unchanged lock does not rebuild panel.c; a changed one reconfigures
# (CMAKE_CONFIGURE_DEPENDS below), which is when the component manager
# would have changed it anyway.

set(_root "${CMAKE_CURRENT_LIST_DIR}/..")
get_filename_component(_root "${_root}" ABSOLUTE)
set(_lock "${_root}/dependencies.lock")
set(_libs "")

# A 40-hex git commit as its first seven; anything else as written.
function(_lv_short out ver)
    string(LENGTH "${ver}" _len)
    if(_len EQUAL 40 AND ver MATCHES "^[0-9a-f]+$")
        string(SUBSTRING "${ver}" 0 7 ver)
    endif()
    set(${out} "${ver}" PARENT_SCOPE)
endfunction()

if(EXISTS "${_lock}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_lock}")
    file(STRINGS "${_lock}" _lines)
    set(_name "")
    set(_in_deps FALSE)
    foreach(_l IN LISTS _lines)
        if(_l STREQUAL "dependencies:")
            set(_in_deps TRUE)
        elseif(_l MATCHES "^[a-z_]+:")          # direct_dependencies, target, ...
            set(_in_deps FALSE)
        elseif(_in_deps AND _l MATCHES "^  ([^ ][^:]*):$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_in_deps AND _name AND _l MATCHES "^    version: '?([^']*)'?$")
            # Four spaces: the component's own version. A dependency's
            # requirement is indented further and does not match.
            set(_ver "${CMAKE_MATCH_1}")
            string(REGEX REPLACE "^espressif/" "" _short "${_name}")
            if(NOT _short STREQUAL "idf" AND NOT _short STREQUAL "cmake_utilities")
                _lv_short(_ver "${_ver}")
                list(APPEND _libs "${_short} ${_ver}")
            endif()
            set(_name "")
        endif()
    endforeach()
else()
    list(APPEND _libs "dependencies.lock missing")
endif()

foreach(_c usb_host_msc usb_host_uac)
    set(_yml "${_root}/components/${_c}/idf_component.yml")
    if(EXISTS "${_yml}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_yml}")
        file(STRINGS "${_yml}" _v REGEX "^version:")
        string(REGEX REPLACE "^version: *\"?([^\"]*)\"?.*$" "\\1" _v "${_v}")
        list(APPEND _libs "${_c} ${_v}, patched")
    endif()
endforeach()

foreach(_pair "minimp3;MINIMP3_COMMIT" "pngle;PNGLE_COMMIT" "stb_image;STB_COMMIT")
    list(GET _pair 0 _n)
    list(GET _pair 1 _var)
    if(DEFINED ${_var})
        _lv_short(_v "${${_var}}")
        list(APPEND _libs "${_n} ${_v}")
    endif()
endforeach()

set(_ark "${_root}/tools/gen_ark12.py")
if(EXISTS "${_ark}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_ark}")
    file(STRINGS "${_ark}" _v REGEX "^ARK_COMMIT *=")
    string(REGEX REPLACE "^ARK_COMMIT *= *\"([0-9a-f]+)\".*$" "\\1" _v "${_v}")
    _lv_short(_v "${_v}")
    list(APPEND _libs "Ark Pixel font ${_v}")
endif()

list(LENGTH _libs _n)
set(_h "/* Generated by cmake/libversions.cmake (5283). Do not edit. */\n")
string(APPEND _h "#pragma once\n#define LIBVERSIONS_COUNT (${_n})\n")
string(APPEND _h "static const char *const k_libversions[LIBVERSIONS_COUNT] = {\n")
foreach(_l IN LISTS _libs)
    string(APPEND _h "    \"${_l}\",\n")
endforeach()
string(APPEND _h "};\n")

set(LIBVERSIONS_DIR "${CMAKE_BINARY_DIR}/libversions")
file(WRITE "${LIBVERSIONS_DIR}/libversions.h.tmp" "${_h}")
configure_file("${LIBVERSIONS_DIR}/libversions.h.tmp"
               "${LIBVERSIONS_DIR}/libversions.h" COPYONLY)
message(STATUS "libversions: ${_n} libraries for the BUILD tab")
